USE ROLE AICOLLEGE;

-- Create retraining model data table
CREATE OR REPLACE TABLE AICOLLEGE.PUBLIC.NEWTRAININGDATA (
    WEEK_START_DATE TIMESTAMP_NTZ,
    WEEK NUMBER(38, 0),
    LOAN_ID NUMBER(38, 0),
    TS VARCHAR,
    LOAN_TYPE_NAME VARCHAR,
    LOAN_PURPOSE_NAME VARCHAR,
    APPLICANT_INCOME_000S NUMBER(38, 0),
    LOAN_AMOUNT_000S NUMBER(38, 0),
    COUNTY_NAME VARCHAR,
    MORTGAGERESPONSE NUMBER(38, 0)
);

-- Load the enriched dataset from your Snowflake stage
COPY INTO AICOLLEGE.PUBLIC.NEWTRAININGDATA
FROM @AICOLLEGE.PUBLIC.SETUP
FILES = ('NewTrainingData.csv')  -- Case-sensitive match required
FILE_FORMAT = aicollege.public.mlops
ON_ERROR = CONTINUE;
